# Generated by Django 2.2.6 on 2020-06-13 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0006_auto_20200614_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='full_name',
            field=models.CharField(max_length=400),
        ),
    ]
